version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout

      - run:
          name: Install Jekyll
          command: gem install jekyll

      - run:
          name: Install dependencies
          command: bundle install

      - run:
          name: Build site
          command: bundle exec jekyll build

      - save_cache:
          key: "app-{{ .Revision }}"
          paths:
            - _site

  deploy:
    docker:
      - image: quantcdn/cli
    steps:
      - restore_cache:
          keys:
            - "app-{{ .Revision }}"
      - run:
          name: Deploy to Quant!
          command: quant deploy /home/circleci/project/_site -c ${QUANT_CUSTOMER} -t ${QUANT_TOKEN} -p ${QUANT_PROJECT}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
